# Generated by Django 4.1.7 on 2023-03-30 08:37

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('eventCode', models.CharField(max_length=255)),
                ('eventName', models.CharField(max_length=255)),
                ('updateTime', models.DateTimeField()),
                ('eqpId', models.IntegerField()),
                ('eqpCode', models.CharField(max_length=255)),
                ('eqpName', models.CharField(max_length=255)),
                ('eqpModuleId', models.IntegerField()),
                ('eqpModuleName', models.CharField(max_length=255)),
                ('context', djongo.models.fields.JSONField(default={})),
                ('fdcDataGroup', djongo.models.fields.GenericObjectIdField()),
            ],
        ),
        migrations.CreateModel(
            name='FdcDataGroup',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('eqpId', models.IntegerField()),
                ('eqpCode', models.CharField(max_length=255)),
                ('eqpName', models.CharField(max_length=255)),
                ('eqpModuleId', models.IntegerField()),
                ('eqpModuleName', models.CharField(max_length=255)),
                ('context', djongo.models.fields.JSONField(default={})),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TraceData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('traceGroupCode', models.CharField(max_length=255)),
                ('traceGroupName', models.CharField(max_length=255)),
                ('value', djongo.models.fields.JSONField(default={})),
                ('eqpId', models.IntegerField()),
                ('eqpCode', models.CharField(max_length=255)),
                ('eqpName', models.CharField(max_length=255)),
                ('eqpModuleId', models.IntegerField()),
                ('updateTime', models.DateTimeField()),
                ('fdcDataGroup', djongo.models.fields.GenericObjectIdField()),
            ],
        ),
    ]
