# Generated by Django 4.1.7 on 2023-03-29 02:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0002_eventgrouphistory_eventhistory_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgrouphistory',
            name='id',
        ),
        migrations.AddField(
            model_name='eventgrouphistory',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default={}, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventgrouphistory',
            name='endEventId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventgrouphistory',
            name='startEventId',
            field=models.IntegerField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='endContext',
            field=djongo.models.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='endEventCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='endEventName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='endEventTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='eqpModuleId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='eqpModuleName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
