# Generated by Django 4.1.7 on 2023-03-29 02:28

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0003_remove_eventgrouphistory_id_eventgrouphistory__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='id',
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default={}, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='endContext',
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='startContext',
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
