# Generated by Django 4.1.7 on 2023-03-29 08:24

from django.db import migrations, models
import djongo.models.fields
import mcp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0004_remove_eventhistory_id_eventhistory__id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FdcDataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqpId', models.IntegerField()),
                ('eqpCode', models.CharField(max_length=100)),
                ('eqpName', models.CharField(max_length=100)),
                ('eqpModuleId', models.IntegerField()),
                ('eqpModuleName', models.CharField(max_length=100)),
                ('context', djongo.models.fields.JSONField(default={})),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('events', djongo.models.fields.ArrayField(model_container=mcp.models.EventHistory)),
            ],
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='endEventTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventgrouphistory',
            name='startEventTime',
            field=models.DateTimeField(),
        ),
    ]
