# Generated by Django 4.1.7 on 2023-03-30 00:15

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0005_fdcdatagroup_alter_eventgrouphistory_endeventtime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventGroupHistory',
        ),
        migrations.RemoveField(
            model_name='fdcdatagroup',
            name='events',
        ),
        migrations.RemoveField(
            model_name='fdcdatagroup',
            name='id',
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='fdcDataGroup',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fdcdatagroup',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='context',
            field=djongo.models.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='eqpCode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='eqpModuleName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='eqpName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='eventCode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fdcdatagroup',
            name='eqpCode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fdcdatagroup',
            name='eqpModuleName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fdcdatagroup',
            name='eqpName',
            field=models.CharField(max_length=255),
        ),
    ]
