# Generated by Django 4.1.7 on 2023-03-30 04:08

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0006_delete_eventgrouphistory_remove_fdcdatagroup_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhistory',
            name='fdcDataGroup',
            field=djongo.models.fields.GenericObjectIdField(),
        ),
    ]
