# Generated by Django 4.1.7 on 2023-03-30 05:00

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0007_alter_eventhistory_fdcdatagroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('traceGroupCode', models.CharField(max_length=255)),
                ('traceGroupName', models.CharField(max_length=255)),
                ('valueName', models.CharField(max_length=255)),
                ('value', models.Field()),
                ('eqpId', models.IntegerField()),
                ('eqpCode', models.CharField(max_length=255)),
                ('eqpName', models.CharField(max_length=255)),
                ('eqpModuleId', models.IntegerField()),
                ('updateTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='eventName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='updateTime',
            field=models.DateTimeField(),
        ),
    ]
