# Generated by Django 4.1.7 on 2023-03-30 05:00

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0008_tracedata_alter_eventhistory_eventname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracedata',
            name='value',
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
