# Generated by Django 4.1.7 on 2023-03-30 05:01

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0009_alter_tracedata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracedata',
            name='fdcDataGroup',
            field=djongo.models.fields.GenericObjectIdField(default=None),
            preserve_default=False,
        ),
    ]
