# Generated by Django 4.1.7 on 2023-03-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0010_tracedata_fdcdatagroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracedata',
            name='valueName',
        ),
    ]
